version: "3.8"

services:
  postgres-service:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - describly
    volumes:
      - describly_postgres_data:/var/lib/postgresql/data

  adminer-service:
    image: adminer:latest
    restart: unless-stopped
    container_name: adminer
    depends_on:
      - postgres-service
    ports:
      - "8080:8080"
    networks:
      - describly

  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi
    container_name: fastapi
    restart: unless-stopped
    depends_on:
      - postgres-service
    ports:
      - "8000:8000"
    networks:
      - describly
    volumes:
      - .:/usr/srv
    env_file:
      - .env

  smtp-service:
    image: axllent/mailpit
    restart: unless-stopped
    container_name: smtp
    networks:
      - describly
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  describly:

volumes:
  describly_postgres_data:
